configserver:
    name: JHipster Test for Spring Cloud Config with an SSH configuration source
    status: ${spring.cloud.config.uri}/${spring.cloud.config.label}/${spring.cloud.config.name}-${spring.cloud.config.profile}.yml/

test: test Github
